### ISSUE TITLE
Round the paddle angle

### ISSUE THREAD

**Issue by Natim** [magopian/elm-pong#3]
With the current condition, the contact is made between the center of the ball and a point of the pad.

However, sometime, the center doesn't hit the pad but the ball does.
Especially in the angle.

We could:

 - Change the condition to handle this case
 - Round the pad so that this case doesn't happens anymore.

**Comment by Natim** [comment]
![image](https://user-images.githubusercontent.com/229453/62541923-0cee7680-b85b-11e9-908a-f46eb3616d65.png)

**Comment by magopian** [comment]
I was thinking about dealing with this in the 4th blog post: in the original pong
- the ball is a square, so the hitbox is simpler to check
- the paddle bounces the ball with an angle: the closer to the edge the ball gets, the bigger the angle (see [The Ball <-> Racket Collision Angle](https://noobtuts.com/unity/2d-pong-game))

**Comment by magopian** [comment]
This is now fixed in https://github.com/magopian/elm-pong/commit/869c3592958baf5573c86039228b88f932ebce42


Thanks @Natim !
